### ISSUE TITLE
Missing attribution to Fabio Ottavi

### ISSUE THREAD

**Issue by frankmorgner** [PersoSim/de.persosim.driver.win#1]
Finally, the BSI Congress is approaching ;-)

The code has obviously been bootstrapped from this project: http://www.codeproject.com/Articles/134010/An-UMDF-Driver-for-a-Virtual-Smart-Card-Reader. Your code is missing the reference to the original author.

You are changing the license to GPLv3. Did you check whether that's compatible with the original License CPOL http://www.codeproject.com/info/cpol10.aspx?

**Comment by hfunke** [comment]
Thanks for your feedback, Frank. Yes, we are looking forward to the BSI Congress :)
Since our first release in December 2013 we are referencing the project of Fabio Ottavi (and also the UMDF sample of Microsoft) in a ReadMe.txt. This ReadMe.txt is also stored here in the repo. On this way there IS a reference to Fabios project. I will transfer the ReadMe.txt into ReadMe.md to integrate Fabios project directly as an URL.
Concerning the license: until it's not clear, we also reference the CPOL since our first release of the win driver.
